# -*- coding: utf-8 -*-
"""scoresight.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_BZHFkvR7RAV_anExzUlYpA8GiJaqZZ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = "/content/dataset - 2020-09-24.csv"
df = pd.read_csv(file_path)
df.head()

df.info()

df.shape

df.tail()

df.describe()

df.head()

df.columns
df.head()
df.info()

df.isnull().sum()

# 1. EXPLORE COLUMN
# Show all column names
print("All Columns:")
print(df.columns.tolist(), "\n")

# 2. IDENTIFY USEFUL COLUMNS
useful_columns = [
    'Goals', 'Assists', 'Appearances', 'Shots',
    'Shots on target', 'Passes', 'Pass accuracy %',
    'Big chances created', 'Key passes'
]

print("Useful Columns for Prediction:")
print(useful_columns, "\n")

# 3. IRRELEVANT COLUMNS (optional drop list)
irrelevant_columns = [
    'Name', 'Jersey Number', 'Nationality', 'Club'
]

print("Irrelevant Columns:")
print(irrelevant_columns, "\n")

import numpy as np

for col in useful_columns:
    if col in df.columns:
        if df[col].dtype != 'object':  # numeric check
            mean_value = df[col].replace(0, np.nan).mean()
            df[col] = df[col].replace(0, np.nan).fillna(mean_value)

print("Missing values handled (0/NaN replaced with mean).")

df.describe()